### ISSUE TITLE
FPS and Processor Usage

### ISSUE THREAD

**Issue by danishnazir** [wb666greene/SecurityDVR_AI_addon#1]
Hi there good work i just wanted to know the FPS and processor usage on PI with Intel Movidus

**Comment by wb666greene** [comment]
Sorry, I didn't get a notice that you had posted.  I'm about to put up a much improved and "final" version for the NCS and found your ask.

I never really measured the frame rate for this system since the rate is limited by how fast the images can arrive via ftp.  But a Pi3B+ servicing my Lorex DVR has been handling the motion detection ftp'd images from 9 cameras for close to a year now without problems.

The new version I'm getting ready to upload does ~6.5 fps on a Pi3B+ with 1 NCS and ~11 fps withi 2 NCS, but 2 NCS is unreliable -- get "Timeout Errors" from the API, I think its power supply related as the "normal 2.4A Pi power supply is probably not enough for two Movidius.  Perhaps I should try with a powered hub, but I'm moving on to OpenVINO and the NCS2 or the new Google Coral TPU.

The OpenVINO code transparently supports NCS or NCS2 and I'm finding the NCS2 is 2-3X faster than the original NCS.  The original NCS SDK is a deadend, v2 was just different, not better as far as I could tell, and didn't support the NCS2.

In addition to ftp, my new verison directly supports network cameras via rtsp streams or  HTTP "jpeg snapshot" URLs.
